https://pokeapi.co/api/v2/egg-group/

###
https://pokeapi.co/api/v2/pokemon/?limit=9999

###
https://pokeapi.co/api/v2/pokemon/pichu/

###
https://pokeapi.co/api/v2/pokemon-species/pichu

###
https://pokeapi.co/api/v2/evolution-chain/18

###
https://pokeapi.co/api/v2/gender/2
